#
# default configuration
#


spring:
   # devtools enabled
   devtools:
      livereload:
         enabled: true
   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://localhost:3306/webdb?characterEncoding=utf8
      username: webdb
      password: webdb   
         
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

# Tomcat Server
server:
   port: 0
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true    
# Eureka
eureka:
   client:
      #       
      fetchRegistry: true
      #
      registerWithEureka: true
      #
      serviceUrl:
         defaultZone: http://localhost:8761/eureka   